### ISSUE TITLE
Usage with Elixir

### ISSUE THREAD

**Issue by luisivan** [larshesel/merkle_tree#1]
Hi Lars,

First of all thanks for this repo! I'm building something in Elixir that makes a heavy use of Merkle trees and this is really helpful

However I'm kind of an Elixir newcomer, do you have any code examples of using this module with 
Elixir instead of Erlang?

Thanks,
Luis

**Comment by larshesel** [comment]
@luisivan Hi there - great you find it helpful. Be aware that it's not very complete and I stopped working on it almost two years ago (but still find the topic super interesting).  There might be much better options out there such as https://github.com/ferd/merklet.

I don't have any examples of using it from elixir, and the project structure is not perfect to be used as a dependency, but I just tried to add it as a mix dependency:

  defp deps do
    [{:mtree_core, git: "https://github.com/larshesel/merkle_tree"}]
  end

And then after getting dependencies and compiling I can access the modules directly from `iex`: 

``` elixir
iex(11)> :mtree.new |> :mtree.insert(:root, <<>>) |> :mtree.insert(:left_leaf, <<0 :: size(1)>>) |> :util.count_nodes 
3
```

If you're experiencing other issues, please let me know.

**Comment by luisivan** [comment]
@larshesel thanks! Yeah, though I have to say that for my use yours it's much elegant and simple.

So, after inserting, I see you call _build_tree_bottom_up_ and I suppose after that you could call _hash_ to get the Merkle root, right?

Thanks a lot

**Comment by larshesel** [comment]
Actually that's way is not supported. mtree:insert was thought to be exactly what you're describing and be used to build dynamic trees. I never got around to finishing it, but would be happy to accept a PR for that.

So for now, the only way to create a tree with hashes in there is to create a list of leaves and pass them to build_tree_bottom_up. Then you can get the hash directly from the tree structure passed back. Here's an example which takes raw data and creates a tree of 1 byte chunks (max one byte per leaf node):

``` elixir
iex(10)> {:inner, root_hash, _,_} = <<1,2,3,4>> |> :mtree_raw.build_tree(1)
{:inner,
 <<190, 211, 211, 58, 129, 2, 111, 123, 233, 58, 239, 173, 68, 197, 137, 28, 39, 252, 130, 101, 170, 21, 39, 154, 88, 226, 135, 116, 75, 124, 119, 83>>,
 {:inner,
  <<161, 40, 113, 254, 226, 16, 251, 134, 25, 41, 30, 174, 161, 148, 88, 28, 189, 37, 49, 228, 178, 55, 89, 210, 37, 246, 128, 105, 35, 246, 50, 34>>,
  {:leaf, <<1>>}, {:leaf, <<2>>}},
 {:inner,
  <<12, 227, 148, 11, 235, 242, 178, 42, 93, 33, 8, 236, 240, 195, 104, 160, 84, 28, 126, 60, 69, 112, 63, 133, 64, 146, 27, 78, 175, 200, 41, 71>>,
  {:leaf, <<3>>}, {:leaf, <<4>>}}}
iex(11)> root_hash
<<190, 211, 211, 58, 129, 2, 111, 123, 233, 58, 239, 173, 68, 197, 137, 28, 39, 252, 130, 101, 170, 21, 39, 154, 88, 226, 135, 116, 75, 124, 119, 83>>
```

**Comment by luisivan** [comment]
Thanks! Thought that was supported, cool anyway. BTW, is it possible to create Merkle proofs (cryptographic proofs that a given subset of data belongs to the tree) by using this?

**Comment by larshesel** [comment]
@luisivan I haven't added that specific functionality, but it shouldn't be hard to do. Again, there are for certain more complete merkle-tree implementations out there which might get you further faster. Otherwise I'll happily accept PRs. I'd like to extend this project, but I'm short on time for it at the moment...
